name: Build, publish and deploy a docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta_react_app
        with:
          images: ghcr.io/natalia-lypovyk/test-react-page

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta_react_app.outputs.tags }}
          labels: ${{ steps.meta_react_app.outputs.labels }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: Deploy image
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: |
          echo "Pull image"
          docker pull ghcr.io/natalia-lypovyk/test-react-page:main
          echo "Stop old version"
          docker stop react-main || true && docker rm react-main || true
          echo "Run new image version"
          docker run -d -p 8001:80 --name react-main ghcr.io/natalia-lypovyk/test-react-page:main
          echo "Remove old image tags"
          docker rmi `docker images | grep "ghcr.io/natalia-lypovyk/test-react-page" |  grep "<none>" | awk {'print $3'}` || true
